config/routes.rb
Rails.application.routes.draw do
  root "home#frontpage"

  #Home
  match '/home' => 'home#home', via: [:get]

  #Search
  match '/search', to: 'search#index', via: [:get], as: 'search'

  #Users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  match '/users/:id/presentations' => 'users#show_presentations', via: [:get]
  match '/users/:id/files' => 'users#show_files', via: [:get]
  match '/users/:id/embeds' => 'users#show_embeds', via: [:get]

  #Documents
  resources :embeds
  resources :links
  resources :documents
  resources :pictures
  resources :zipfiles
  resources :officedocs
  resources :scormfiles
  match '/documents/:id/download' => 'documents#download', :via => :get
  match '/pictures/:id/download' => 'documents#download', :via => :get
  match '/zipfiles/:id/download' => 'documents#download', :via => :get
  match '/officedocs/:id/download' => 'documents#download', :via => :get
  match '/scormfiles/:id/download' => 'scormfiles#download', :via => :get

  #Presentations
  match '/presentations/:id/metadata' => 'presentations#metadata', :via => :get
  match '/presentations/:id/scormMetadata' => 'presentations#scormMetadata', :via => :get
  match '/presentations/:id/clone' => 'presentations#clone', :via => :get
  match '/presentations/last_slide' => 'presentations#last_slide', :via => :get
  match '/presentations/preview' => 'presentations#preview', :via => :get
  match '/presentations/tmpJson' => 'presentations#uploadTmpJSON', :via => :post
  match '/presentations/tmpJson' => 'presentations#downloadTmpJSON', :via => :get
  resources :presentations

  #PDF to Presentation
  resources :pdfps, :except => [:index]

  #Locale
  match '/change_locale', to: 'locales#change_locale', via: [:get]

  #Thumbnails
  match '/thumbnails' => 'presentations#presentation_thumbnails', via: [:get]

  #Tags
  match "/tags" => 'tags#index', :via => :get

  #Terms of use
  match '/terms_of_use', to: "home#frontpage", via: [:get]

  #Wildcard route (This rule should be placed the last)
  match "*not_found", :to => 'application#page_not_found', via: [:get]
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  require 'fileutils'
  before_action :authenticate_user!, :only => [ :new, :create, :edit, :update, :clone, :uploadTmpJSON ]
  load_and_authorize_resource :except => [:metadata]
  before_action :allow_iframe_requests, :only => [:show]

  # Enable CORS
  before_action :cors_preflight_check, :only => [:presentation_thumbnails, :last_slide, :iframe_api]
  after_action :cors_set_access_control_headers, :only => [:presentation_thumbnails, :last_slide, :iframe_api]
  
  #############
  # REST methods
  #############

  def index
    redirect_to "/"
  end

  def show
    @presentation = Presentation.find(params[:id])
    @suggestions = RecommenderSystem.suggestions({:n => 6, :lo_profile => @presentation.profile, :settings => {:preselection_filter_by_resource_types => ["Presentation"]}})
    respond_to do |format|
      format.html {
        if @presentation.draft 
          if (can? :edit, @presentation)
            redirect_to edit_presentation_path(@presentation)
          else
            redirect_to "/"
          end
        else
          render
        end
      }
      format.full {
        render :layout => 'veditor'
      }
      format.json {
        render :json => @presentation.json
      }
      format.scorm {
        if (can? :read, @presentation)
          scormVersion = (params["version"].present? and ["12","2004"].include?(params["version"])) ? params["version"] : "2004"
          @presentation.to_scorm(self,scormVersion)
          send_file @presentation.scormFilePath(scormVersion), :type => 'application/zip', :disposition => 'attachment', :filename => ("scorm" + scormVersion + "-#{@presentation.id}.zip")
        else
          render :nothing => true, :status => 500
        end
      }      
    end
  end

  def new
    @presentation = Presentation.new
    respond_to do |format|
      format.full { render :layout => 'veditor', :locals => {:default_tag=> params[:default_tag]}}
    end
  end

  def edit
    @presentation = Presentation.find(params[:id])
    respond_to do |format|
      format.full { render :layout => 'veditor' }
    end
  end

  def create
    params[:excursion].permit!
    @presentation = Presentation.new(params[:excursion])

    if(params[:draft] and params[:draft] == "true")
      @presentation.draft = true
    else
      @presentation.draft = false
    end
    
    @presentation.views = 0
    @presentation.owner_id = current_user.id
    @presentation.save!

    published = (@presentation.draft===false)
    if published
      @presentation.afterPublish
    end

    render :json => { :url => (@presentation.draft ? user_path(current_user) : presentation_path(@presentation)),
                      :uploadPath => presentation_path(@presentation, :format=> "json"),
                      :editPath => edit_presentation_path(@presentation),
                      :id => @presentation.id
                    }
  end

  def update
    params[:excursion].permit! unless params[:excursion].blank?

    @presentation = Presentation.find(params[:id])
    wasDraft = @presentation.draft

    if(params[:draft])
      if(params[:draft] == "true")
        @presentation.draft = true
      elsif (params[:draft] == "false")
        @presentation.draft = false
      end
    end

    @presentation.update!(params[:excursion] || {})
   
    published = (wasDraft===true and @presentation.draft===false)
    if published
      @presentation.afterPublish
    end

    render :json => { :url => (@presentation.draft ? user_path(current_user) : presentation_path(@presentation)),
                      :uploadPath => presentation_path(@presentation, :format=> "json"),
                      :editPath => edit_presentation_path(@presentation),
                      :exitPath => (@presentation.draft ? user_path(current_user) : presentation_path(@presentation)),
                      :id => @presentation.id
                    }
  end

  def destroy
    @presentation = Presentation.find(params[:id])
    @presentation.destroy
    respond_to do |format|
      format.all { 
        redirect_to view_context.current_user_path_for("presentations")
      }
    end
  end


  ############################
  # Custom actions over Presentations and services provided by presentations controller
  ############################

  def preview
    respond_to do |format|
      format.all { render "show", :formats => [:full], :layout => 'veditor' }
    end
  end

  def metadata
    presentation = Presentation.find_by_id(params[:id])
    authorize! :show, presentation
    respond_to do |format|
      format.any {
        unless presentation.nil?
          xmlMetadata = Presentation.generate_LOM_metadata(JSON(presentation.json),presentation,{:id => Rails.application.routes.url_helpers.presentation_url(:id => presentation.id), :LOMschema => params[:LOMschema] || "custom"})
          render :xml => xmlMetadata.target!, :content_type => "text/xml"
        else
          xmlMetadata = ::Builder::XmlMarkup.new(:indent => 2)
          xmlMetadata.instruct! :xml, :version => "1.0", :encoding => "UTF-8"
          xmlMetadata.error("Presentation not found")
          render :xml => xmlMetadata.target!, :content_type => "text/xml", :status => 404
        end
      }
    end
  end

  def scormMetadata
    presentation = Presentation.find_by_id(params[:id])
    scormVersion = ((params["version"].present? and ["12","2004"].include?(params["version"])) ? params["version"] : "2004")
    respond_to do |format|
      format.xml {
        xmlMetadata = Presentation.generate_scorm_manifest(scormVersion,JSON(presentation.json),presentation,{:LOMschema => params[:LOMschema]})
        render :xml => xmlMetadata.target!
      }
      format.any {
        redirect_to (presentation_path(presentation)+"/scormMetadata.xml?version=" + scormVersion)
      }
    end
  end

  def clone
    original = Presentation.find_by_id(params[:id])
    if original.blank?
      flash[:alert] = t('dictionary.errors.resource_not_found')
      redirect_to presentation_path(original)
    else
      cloned_presentation = original.clone_for(current_user)
      if cloned_presentation.nil?
        flash[:notice] = t('presentations.clone.fail')
        redirect_to presentation_path(original)
      else
        flash[:notice] = t('presentations.clone.success')
        redirect_to presentation_path(cloned_presentation)
      end
    end
  end

  def manifest
    headers['Last-Modified'] = Time.now.httpdate
    @presentation = Presentation.find_by_id(params[:id])
    render 'cache.manifest', :layout => false, :content_type => 'text/cache-manifest'
  end

  def iframe_api
    respond_to do |format|
      format.js {
        render :file => "#{Rails.root}/lib/plugins/vish_editor/app/assets/javascripts/VISH.IframeAPI.js",
          :content_type => 'application/javascript',
          :layout => false
      }
    end
  end

  def presentation_thumbnails
    thumbnails = Hash.new
    thumbnails["pictures"] = []

    81.times do |index|
      index = index+1
      thumbnail = Hash.new
      thumbnail["title"] = "Thumbnail " + index.to_s
      thumbnail["description"] = "Sample Thumbnail"
      tnumber = index.to_s
      if index<10
        tnumber = "0" + tnumber
      end
      thumbnail["src"] = Movle::Application.config.full_domain + "/assets/logos/original/excursion-"+tnumber+".png"
      thumbnail["src"] = Utils.checkUrlProtocol(thumbnail["src"],request.protocol)
      thumbnails["pictures"].push(thumbnail)
    end

    render :json => thumbnails
  end


  ##################
  # Recomendation on the last slide
  ##################
  
  def last_slide
    current_presentation =  Presentation.find_by_id(params[:presentation_id]) if params[:presentation_id]
    options = {:user => current_user, :lo => current_presentation, :n => (params[:quantity] || 6).to_i, :models => [Presentation]}
    options[:keywords] = params[:q].split(",") if current_presentation.nil? and params[:q]
    presentations = RecommenderSystem.suggestions(options).map { |profile|
      {
        :id => profile[:id_repository],
        :url => profile[:url],
        :title => profile[:title],
        :description => profile[:description],
        :author => profile[:object].owner.name,
        :image => profile[:thumbnail_url],
        :views => "",
        :favourites => ""
      }
    }
    respond_to do |format|
      format.json {
        render :json => presentations
      }
    end
  end


  #####################
  ## VE Methods
  ####################

  def uploadTmpJSON
    respond_to do |format|  
      format.json {
        results = Hash.new
        return render :json => results unless params["json"].present?
        json = params["json"]
        
        responseFormat = "json" #Default
        if params["responseFormat"].is_a? String
          responseFormatParsedParam = params["responseFormat"].downcase
          if responseFormatParsedParam.include?("scorm")
            responseFormat = "scorm"
            scormVersion = responseFormatParsedParam.sub("scorm","")
          elsif responseFormatParsedParam == "qti"
            responseFormat = "qti"
          elsif responseFormatParsedParam == "moodlexml"
            responseFormat = "MoodleXML"
          end
        end

        tmpFileName = Time.now.to_i.to_s

        if responseFormat == "json"
          #Generate JSON file
          filePath = "#{Rails.root}/public/tmp/json/#{tmpFileName}.json"
          t = File.open(filePath, 'w')
          t.write json
          t.close
          results["url"] = "#{Movle::Application.config.full_domain}/presentations/tmpJson.json?fileId=#{tmpFileName}"
        elsif responseFormat == "scorm" and ["12","2004"].include?(scormVersion)
          #Generate SCORM package
          filePath = "#{Rails.root}/public/tmp/scorm/"
          fileName = "scorm" + scormVersion + "-tmp-#{tmpFileName}"
          Presentation.createSCORM(scormVersion,filePath,fileName,JSON(json),nil,self)

app/views/presentations/_embedcode.html.erb
&lt;iframe src='//<%= request.env["HTTP_HOST"] + presentation_path(presentation, :format => :full)%>' width='910' height='680' style='border:0' iframeborder='0' frameborder='0' iframeElement.frameBorder = 0; webkitallowfullscreen mozallowfullscreen allowfullscreen &gt;&lt;/iframe&gt

app/views/presentations/_presentation.html.erb
<% generated_id= "presentation-" + presentation.id.to_s %>
<div class="item_box">
  <div class="item_icon">
    <a href=<%=  presentation_url(presentation) %>>
      <img src="/assets/slides_num.png"/>
    </a>
  </div>
  <div class="item_thumbnail <%="item_thumbnail_draft_wrapper" if presentation.draft %>">
      <%= link_to(presentation_url(presentation)) do %>
        <div class="item_thumbnail_img" id="<%=generated_id%>"></div>
      <%end%>
    </div>
    <div class="item_title">
      <%= link_to(presentation_url(presentation)) do %>
        <p class="title"><%= presentation.title %></p>
      <%end%>
    </div>
    <div class="item_user">
      <div class="d-flex by_date justify-content-between">
        <span class="author">
          <span class="by"><%=t('by')%></span>
          <%= link_to User.find_by(id: presentation.owner_id)&.name, user_path(presentation.owner_id) if presentation.owner_id.present? %>
        </span>
        <span><%= presentation.created_at.strftime('%d/%m/%Y') %></span>
      </div>
      <div class="d-flex views_after_by">
        <i class="bi bi-eye-fill"></i>
        <p><%=presentation.views%> <%=t('presentations.views')%></p>
      </div>
    </div>
  </div>
  <script>
    document.getElementById("<%=generated_id%>").style.backgroundImage = "url('<%=presentation.thumbnail_url%>')";
  </script>

app/views/presentations/_presentation_show.html.erb
 <%=javascript_include_tag "VISH.IframeAPI" %>

<script type="text/javascript">
//VE extra vars
var options = {};
options["readHashFromParent"] = true;
</script>

<iframe class="vishEditorIframe" src="<%=presentation_path(presentation, :format => :full)%>" width="100%" height="100%" iframeborder="0" frameborder="0" iframeElement.frameBorder = 0; webkitAllowFullScreen="true" allowfullscreen="true" mozallowfullscreen="true">
</iframe>

app/views/presentations/edit.full.erb
<%= javascript_include_tag 've_movle_locales' %>
<%= render :partial => 'vish_editor' %>

<script>	
	options = {};
	var configuration = {};

	configuration["ImagesPath"] = "/assets/";
	configuration["StylesheetsPath"] = "/assets/";

	configuration["uploadPresentationPath"] = "<%= presentation_path @presentation, :format=> "json" %>";
	configuration["previewPresentationPath"] = "/presentations/preview";

	configuration["uploadImagePath"] = "<%= documents_path :format=> "json"%>";
	// configuration["uploadObjectPath"] = "<%= documents_path :format=> "json"%>";
	configuration["uploadPDF2PPath"] = "<%= pdfps_path :format=> "json"%>";
	// configuration["uploadEPackagesPath"] = "<%= documents_path :format=> "json"%>";
	configuration["enableFileImportation"] = true;

	// Sources enabled
	configuration["ViSH"] = true;
	configuration["ViSH_instances"] = ["http://vishub.org","http://educainternet.es"];
	configuration["Flickr"] = true;
	<% unless Movle::Application.config.APP_CONFIG['EuropeanaAPIKEY'].nil? %>
		configuration["Europeana"] = true;
		configuration["EuropeanaAPIKEY"] =  "<%= Movle::Application.config.APP_CONFIG['EuropeanaAPIKEY'] %>";
	<% end %>
	<% unless Movle::Application.config.APP_CONFIG['YouTubeAPIKEY'].nil? %>
		configuration["Youtube"] = true;
		configuration["YoutubeAPIKEY"] =  "<%= Movle::Application.config.APP_CONFIG['YouTubeAPIKEY'] %>";
	<% end %>
	configuration["LRE"] = true;
	configuration["LRE_path"] = "http://vishub.org/lre/search";
	<% unless Movle::Application.config.APP_CONFIG['soundCloudAPIKEY'].nil? %>
		configuration["SoundCloud"] = true;
		configuration["SoundCloudAPIKEY"] =  "<%= Movle::Application.config.APP_CONFIG['soundCloudAPIKEY'] %>";
	<% end %>

	//Thumbnails
	configuration["thumbnailsPath"] = '/thumbnails.json';
	
	//Tags
	configuration["tagsPath"] = "/tags.json?mode=popular&limit=100";
	
	//TmpJSON
	configuration["uploadJSONPath"] = '/presentations/tmpJson'

	//Attachment
	// configuration["uploadAttachmentPath"]
	

	configuration["presentationSettings"] = true;

	var tagsSettings = new Object();
	tagsSettings.maxLength = '<%=Movle::Application.config.tagsSettings["maxLength"]%>';
	tagsSettings.maxTags = '<%=Movle::Application.config.tagsSettings["maxTags"]%>';
	tagsSettings.triggerKeys = <%=raw(Movle::Application.config.tagsSettings["triggerKeys"].to_json)%>;     	
	configuration["tagsSettings"] = tagsSettings;

	configuration["publishPermissions"] = ["Comment","Download","Clone"]

	// Locales
	configuration["defaultLanguage"] = "en";
	configuration["locales"] = VE_MOVLE_Locales;

	//WAPP TOKEN API
	configuration["WAPP_TOKEN_API"] = {
		rootURL: "<%=Movle::Application.config.full_domain%>" + "/apis/wapp_token"
	};

	options["configuration"] = configuration;
	options["developping"] = false;

	options["environment"] = {
		name: "<%= Movle::Application.config.name %>"
	}

	options["user"] = {
		name: "<%= @presentation.owner.name %>",
		id: "<%= @presentation.owner.id %>",
		token: "<%= form_authenticity_token %>"
	};

	options["draft"] = <%= @presentation.draft.to_s %>;

	options["lang"] = "<%= I18n.locale.to_s%>";

	<% if current_user %>
		<% if @presentation.draft.to_s == "false" %>
			options["exitURL"]  = "<%= presentation_path(@presentation) %>";
		<% else %>
			options["exitURL"]  = "<%= url_for(current_user) %>";
		<% end %>
	<% end %>

	options.addons = [];
	var addon = new Object();
	addon.target = "Both";
	addon.id = "IframeMessenger";
	addon.config = {enable: true};
	options.addons.push(addon);

	function start(){
		VISH.Editor.init(options, <%= raw @presentation.to_json%> );
	}
</script>

app/views/presentations/edit.html.erb
<div id="ve_wrapper">
  <iframe class="vishEditorIframe" id="ve_iframe" src="<%=edit_presentation_path(@presentation, :format => :full)%>" width="1200" height="750" style="border:0" iframeborder="0" frameborder="0" iframeElement.frameBorder=0; webkitAllowFullScreen="true" allowfullscreen="true" mozallowfullscreen="true"></iframe>
  <div id="ve_tools_wrapper">
    <a href="<%=presentation_path(@presentation)%>" data-confirm="<%=t('dictionary.are_you_sure')%>" data-ok-button="<%=t('dictionary.ok')%>" data-cancel-button="<%=t('dictionary.cancel')%>" data-method="delete" data-callback="beforeDelete" rel="nofollow">
      <button class="movle_button">
        <span class="glyphicon glyphicon-trash"></span><%=t("dictionary.remove")%>
      </button>
    </a>
  </div>
</div>

<%=javascript_include_tag "VISH.IframeAPI" %>

<script type="text/javascript">
  var VEconnected = false;
  window.onload = function(){
    VISH.IframeAPI.init({callback: onConnect});
  };
  function onConnect(origin){
    // console.log("Communication stablished with " + origin);
    VEconnected = true;
    VISH.IframeAPI.registerCallback("onVEFocusChange",function(focus,origin){
        if((focus===true)&&($('[data-toggle="dropdown"]').length>0)&&($('[data-toggle="dropdown"]').parent().hasClass('open'))){
          $('[data-toggle="dropdown"]').parent().removeClass('open');
        }
    });
  };
  function beforeDelete(result){
    if(result===true){
      if((typeof VISH != "undefined")&&(typeof VISH.IframeAPI != "undefined")&&(typeof VISH.IframeAPI.allowExitWithoutConfirmation == "function")&&(VEconnected===true)){
        VISH.IframeAPI.allowExitWithoutConfirmation();
      }
    }
  };
</script>

app/views/presentations/new.full.erb
<%= javascript_include_tag 've_movle_locales' %>
<%= render :partial => 'vish_editor' %>

<script>	
	options = {};
	var configuration = {};

	configuration["ImagesPath"] = "/assets/";
	configuration["StylesheetsPath"] = "/assets/";

	configuration["uploadPresentationPath"] = "<%= presentations_path :format=> 'json'%>";
	configuration["previewPresentationPath"] = "/presentations/preview";

	configuration["uploadImagePath"] = "<%= documents_path :format=> "json"%>";
	// configuration["uploadObjectPath"] = "<%= documents_path :format=> "json"%>";
	configuration["uploadPDF2PPath"] = "<%= pdfps_path :format=> "json"%>";
	// configuration["uploadEPackagesPath"] = "<%= documents_path :format=> "json"%>";
	configuration["enableFileImportation"] = true;

	// Sources enabled
	configuration["ViSH"] = true;
	configuration["ViSH_instances"] = ["http://vishub.org","http://educainternet.es"];
	configuration["Flickr"] = true;
	<% unless Movle::Application.config.APP_CONFIG['EuropeanaAPIKEY'].nil? %>
		configuration["Europeana"] = true;
		configuration["EuropeanaAPIKEY"] =  "<%= Movle::Application.config.APP_CONFIG['EuropeanaAPIKEY'] %>";
	<% end %>
	<% unless Movle::Application.config.APP_CONFIG['YouTubeAPIKEY'].nil? %>
		configuration["Youtube"] = true;
		configuration["YoutubeAPIKEY"] =  "<%= Movle::Application.config.APP_CONFIG['YouTubeAPIKEY'] %>";
	<% end %>
	configuration["LRE"] = true;
	configuration["LRE_path"] = "http://vishub.org/lre/search";
	<% unless Movle::Application.config.APP_CONFIG['soundCloudAPIKEY'].nil? %>
		configuration["SoundCloud"] = true;
		configuration["SoundCloudAPIKEY"] =  "<%= Movle::Application.config.APP_CONFIG['soundCloudAPIKEY'] %>";
	<% end %>

	//Thumbnails
	configuration["thumbnailsPath"] = '/thumbnails.json';
	
	//Tags
	configuration["tagsPath"] = "/tags.json?mode=popular&limit=100";
	
	//TmpJSON
	configuration["uploadJSONPath"] = '/presentations/tmpJson'

	//Attachment
	// configuration["uploadAttachmentPath"]
	

	configuration["presentationSettings"] = true;

	var tagsSettings = new Object();
	tagsSettings.maxLength = '<%=Movle::Application.config.tagsSettings["maxLength"]%>';
	tagsSettings.maxTags = '<%=Movle::Application.config.tagsSettings["maxTags"]%>';
	tagsSettings.triggerKeys = <%=raw(Movle::Application.config.tagsSettings["triggerKeys"].to_json)%>;     	
	configuration["tagsSettings"] = tagsSettings;

	configuration["publishPermissions"] = ["Comment","Download","Clone"]

	// Locales
	configuration["defaultLanguage"] = "en";
	configuration["locales"] = VE_MOVLE_Locales;

	options["configuration"] = configuration;
	options["developping"] = false;

	options["environment"] = {
		name: "<%= Movle::Application.config.name %>"
	}

	options["user"] = {
		name: "<%= current_user.name %>",
		id: "<%= current_user.id %>",
		token: "<%= form_authenticity_token %>"
	};

	options["draft"] = true;

	options["lang"] = "<%= I18n.locale.to_s%>";

	<% if current_user %>
		options["exitURL"]  = "<%= url_for(current_user) %>";
	<% end %>

	options.addons = [];
	var addon = new Object();
	addon.target = "Both";
	addon.id = "IframeMessenger";
	addon.config = {enable: true};
	options.addons.push(addon);

	function start(){
		VISH.Editor.init(options);
	}
</script>

app/views/presentations/new.html.erb
<div id="ve_wrapper">
  <iframe class="vishEditorIframe" id="ve_iframe" src="<%=new_presentation_path(:format => :full, :default_tag=>params[:default_tag])%>" width="1200" height="750" style="border:0" iframeborder="0" frameborder="0" iframeElement.frameBorder=0; webkitAllowFullScreen="true" allowfullscreen="true" mozallowfullscreen="true"></iframe>
</div>

<%=javascript_include_tag "VISH.IframeAPI" %>

<script type="text/javascript">
  var VEconnected = false;
  window.onload = function(){
    VISH.IframeAPI.init({callback: onConnect});
  };
  function onConnect(origin){
    // console.log("Communication stablished with " + origin);
    VEconnected = true;
    VISH.IframeAPI.registerCallback("onVEFocusChange",function(focus,origin){
        if((focus===true)&&($('[data-toggle="dropdown"]').length>0)&&($('[data-toggle="dropdown"]').parent().hasClass('open'))){
          $('[data-toggle="dropdown"]').parent().removeClass('open');
        }
    });
  };
</script>

app/views/presentations/show.full.erb
<%= javascript_include_tag 've_movle_locales' %>
<%= render :partial => 'presentations/vish_viewer' %>

<script>
	options = {};
	var configuration = {};

	configuration["ImagesPath"] = "/assets/";
	configuration["StylesheetsPath"] = "/assets/";

	// Locales
	configuration["defaultLanguage"] = "en";
	configuration["locales"] = VE_MOVLE_Locales;

	// Recommendations API
	configuration["recommendationsAPI"] = {
		rootURL: "<%=Movle::Application.config.full_domain%>" + "/presentations/last_slide.json"
	};

	//WAPP TOKEN API
	configuration["WAPP_TOKEN_API"] = {
		rootURL: "<%=Movle::Application.config.full_domain%>" + "/apis/wapp_token"
	};

	options["configuration"] = configuration;
	options["developping"] = false;

	//Environment data
	options["environment"] = {
		name: "<%= Movle::Application.config.name %>"
	}

	//User data
	<% if user_signed_in? %>
		options["user"] = {
			name: "<%= current_user.name %>",
			id: "<%= current_user.id %>",
			token: "<%= form_authenticity_token %>"
		};
	<% end %>

	options["lang"] = "<%= I18n.locale.to_s %>";

	//Watermark
	<% if @presentation %>
		options["watermarkURL"] = "<%=presentation_path(@presentation)%>";
	<% end %>

	<% unless params["oreferrer"].blank? %>
		options["referrer"] = "<%=params['oreferrer']%>";
	<% end %>
	
	//Extra options from parent
	try {
		if(typeof window.parent.options != "undefined"){
			options["readHashFromParent"] = window.parent.options["readHashFromParent"];
		}
	} catch(err){}


	options.addons = [];

	var addon = new Object();
	addon.target = "Both";
	addon.id = "IframeMessenger";
	addon.url = "";
	addon.config = {enable: true};
	options.addons.push(addon);


	function start(){
		var isPreview = false;
		try {
			isPreview = window.parent.VISH && 
						window.parent.VISH.Editor && 
						(typeof window.parent.VISH.Editor.Preview.getPreview == "function") && 
						(typeof window.parent.VISH.Editor.Preview.getPreview() != 'undefined') &&
						(window.parent.VISH.Editor.Preview.getPreview() != null);
		} catch(exception) {
			isPreview = false;
		}
		
		var mypresentation;

		if(isPreview){
			options["preview"] = true;
			mypresentation =  window.parent.VISH.Editor.Preview.getPreview();
		} else {
			<% if @presentation %>
				mypresentation = <%= raw @presentation.json %>;
			<% else %>
				mypresentation = null;
			<% end %>
		}
			
		VISH.Viewer.init(options, mypresentation);
	}
</script>

app/views/presentations/show.html.erb
<%= render :partial => 'resources/show', :locals  => { :resource => @presentation } %>

app/views/presentations/show.scorm.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="stylesheets/libs/joyride-1.0.5.css">
	<link rel="stylesheet" type="text/css" href="stylesheets/libs/jquery.fancybox-1.3.4.css"/>
	<link rel="stylesheet" type="text/css" href="stylesheets/libs/jquery-ui-1.9.2.custom.css">
	<link rel="stylesheet" type="text/css" href="stylesheets/all/vishViewer.css">
	<script type="text/javascript" src="javascripts/vishViewer.min.js"></script>
</head>

<body onload="start()" style="display: none" class="loaded" id="presentation_iframe">

	<%= render partial: 'presentations/vish_viewer_scorm', formats: :full %>

	<script>
		options = {};

		var configuration = {};

		configuration["ImagesPath"] = "images/";
		configuration["StylesheetsPath"] = "stylesheets/";

		options["configuration"] = configuration;
		options["developping"] = false;
		
		options["scorm"] = true;

		var presentation = <%= raw json.to_json %>;

		function start(){
			VISH.Viewer.init(options,presentation);
		}
	</script>

</body>
</html>