config/routes.rb
Rails.application.routes.draw do
  root "home#frontpage"

  #Home
  match '/home' => 'home#home', via: [:get]

  #Search
  match '/search', to: 'search#index', via: [:get], as: 'search'

  #Users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  match '/users/:id/presentations' => 'users#show_presentations', via: [:get]
  match '/users/:id/files' => 'users#show_files', via: [:get]
  match '/users/:id/embeds' => 'users#show_embeds', via: [:get]

  #Documents
  resources :embeds
  resources :links
  resources :documents
  resources :pictures
  resources :zipfiles
  resources :officedocs
  resources :scormfiles
  match '/documents/:id/download' => 'documents#download', :via => :get
  match '/pictures/:id/download' => 'documents#download', :via => :get
  match '/zipfiles/:id/download' => 'documents#download', :via => :get
  match '/officedocs/:id/download' => 'documents#download', :via => :get
  match '/scormfiles/:id/download' => 'scormfiles#download', :via => :get

  #Presentations
  match '/presentations/:id/metadata' => 'presentations#metadata', :via => :get
  match '/presentations/:id/scormMetadata' => 'presentations#scormMetadata', :via => :get
  match '/presentations/:id/clone' => 'presentations#clone', :via => :get
  match '/presentations/last_slide' => 'presentations#last_slide', :via => :get
  match '/presentations/preview' => 'presentations#preview', :via => :get
  match '/presentations/tmpJson' => 'presentations#uploadTmpJSON', :via => :post
  match '/presentations/tmpJson' => 'presentations#downloadTmpJSON', :via => :get
  resources :presentations

  #PDF to Presentation
  resources :pdfps, :except => [:index]

  #Locale
  match '/change_locale', to: 'locales#change_locale', via: [:get]

  #Thumbnails
  match '/thumbnails' => 'presentations#presentation_thumbnails', via: [:get]

  #Tags
  match "/tags" => 'tags#index', :via => :get

  #Terms of use
  match '/terms_of_use', to: "home#frontpage", via: [:get]

  #Wildcard route (This rule should be placed the last)
  match "*not_found", :to => 'application#page_not_found', via: [:get]
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    messages = []
    unless flash[:recaptcha_error].blank?
      messages << flash[:recaptcha_error]
      flash[:recaptcha_error] = nil
    end
    messages = (messages + resource.errors.full_messages)
    return "" if messages.empty?

    message = messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: messages.length,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{message}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/resources/_box.html.erb
<% resourceClassName = resource.class.name.underscore %>
<% generated_id= "item-" + resource.item_id %>
<div class="item_box">
  <div class="item_thumbnail <%="item_thumbnail_draft_wrapper" if resource.draft %>">
    <%= link_to(presentation_url(resource)) do %>
      <div class="item_thumbnail_img" id="<%=generated_id%>"></div>
    <%end%>
  </div>
  <div class="item_title">
    <%= link_to(presentation_url(resource)) do %>
      <p class="title"><%= resource.title %></p>
    <%end%>
  </div>
  <div class="item_user">
    <div class="d-flex by_date justify-content-between">
      <span class="author">
        <span class="by"><%=t('by')%></span>
        <%= link_to User.find_by(id: resource.owner_id)&.name, user_path(resource.owner_id) if resource.owner_id.present? %>
      </span>
      <span><%= resource.created_at.strftime('%d/%m/%Y') %></span>
    </div>
    <div class="d-flex views_after_by">
      <i class="bi bi-eye-fill"></i>
      <p><%=resource.views%> <%=t('presentations.views')%></p>
    </div>
  </div>
</div>
<script>
  document.getElementById("<%=generated_id%>").style.backgroundImage = "url('<%=resource.thumbnail_url%>')";
</script>

app/views/resources/_resource.html.erb
<% resourceClassName = resource.class.name.underscore %>
<% if lookup_context.template_exists?(resourceClassName, resourceClassName.tableize, true) %>
  <%= render partial: "#{resourceClassName.tableize}/#{resourceClassName}", locals: { resourceClassName.to_sym => resource } %>
<% else %>
  <% generated_id = (resourceClassName + "-" + resource.id.to_s) %>
  <div class="item_box item_box_<%=resourceClassName%>">
    <div class="item_icon">
      <a href=<%=  polymorphic_url(resource) %>>
				<% if resource.respond_to?("mini_thumbnail_url") %>
					<img src="<%=resource.mini_thumbnail_url%>"/>
				<% else %>
					<img src="/assets/glyphicons-37-file.png"/>
				<% end %>
			</a>
      </div>
      <div class="item_thumbnail">
        <%= link_to(polymorphic_url(resource)) do %>
          <div class="item_thumbnail_img" id="<%=generated_id%>"></div>
        <%end%>
      </div>
      <div class="item_user">
        <div class="item_title">
          <%= link_to(polymorphic_url(resource)) do %>
            <p class="title"><%= resource.title %></p>
          <%end%>
        </div>
        <div class="d-flex by_date justify-content-between">
          <span class="author">
            <span class="by"><%=t('by')%></span>
            <%= link_to User.find_by(id: resource.owner_id)&.name, user_path(resource.owner_id) if resource.owner_id.present? %>
          </span>
          <span><%= resource.created_at.strftime('%d/%m/%Y') %></span>
        </div>
      </div>
    </div>
    <% if resource.respond_to?("thumbnail_url") %>
      <script>
        document.getElementById("<%=generated_id%>").style.backgroundImage = "url('<%=resource.thumbnail_url%>')";
      </script>
    <% end %>
  <% end %>

app/views/resources/_resource_new.html.erb
<div class="item_box">
  <div class="item_thumbnail item_thubmnail_new">
    <%= link_to(new_resource_path) do %>+<%end%>
  </div>
  <div class="item_title" style="margin-bottom: 12px">
    <p class="add_new"><%=t('resources.add_new')%></p>
  </div>
</div>

app/views/resources/_show.html.erb
<% resourceClassName = resource.class.name.underscore %>
<% resourceHeight = resource.respond_to?("height") ? resource.height : nil %>
<% resourceHeight = [1250,resourceHeight].min if (!resourceHeight.nil? && resourceHeight > 0) %>
<section id="resource_wrapper" class="row resource_wrapper_<%=resource.class.name.downcase%>">
  <h3><%= resource.title %></h3>
  <div class="resource_content_tools_wrapper col-md-9">
    <div class="resource_content_wrapper" style="<%=('height:' + resourceHeight.to_s + 'px') unless resourceHeight.nil? %>">
      <%= render :partial => (resourceClassName + '_show'), :locals  => { resourceClassName.to_sym => resource } %>
    </div>
    <div class="resource_tools_wrapper">
      <%= render :partial => 'resources/tools', :locals  => { :resource => resource, :resourceClassName =>  resourceClassName} %>
    </div>
  </div>
  <div class="resource_suggestions_wrapper col-md-3">
    <%= render :partial => "resources/suggestions", :locals  => { :suggestions => @suggestions } %>
  </div>
</section>

app/views/resources/_suggestion.html.erb
<% generated_id= (profile[:object_class] + "-" + profile[:id_repository].to_s) %>
<div class="rsitem_box rsitem_box_<%=profile[:object_class]%>">
  <div class="rsitem_icon">
    <a href=<%= profile[:url] %>>
      <%if profile[:mini_thumbnail_url] %>
        <img src="<%=profile[:mini_thumbnail_url]%>"/>
      <% else %>
        <img src="/assets/glyphicons-37-file.png"/>
      <% end %>
    </a>
    </div>
    <div class="rsitem_thumbnail">
      <%= link_to(profile[:url]) do %>
        <div class="rsitem_thumbnail_img" id="<%=generated_id%>"></div>
      <% end %>
    </div>
    <div class="rsitem_title">
      <%= link_to(profile[:url]) do %>
        <p class="title"><%= profile[:title] %></p>
      <% end %>
    </div>
  </div>
  <% unless profile[:thumbnail_url].blank? %>
    <script>
      document.getElementById("<%=generated_id%>").style.backgroundImage = "url('<%=profile[:thumbnail_url]%>')";
    </script>
  <% end %>

app/views/resources/_suggestions.html.erb
<h4 style="font-size: 25px; font-weight: bold"><%=t("resources.suggestions")%></h4>
<div>
  <% suggestions.each do |profile| %>
    <%= render :partial => 'resources/suggestion', :locals  => { :profile => profile } %>
  <% end %>
</div>

app/views/resources/_tools.html.erb
<% canBeEmbeded = lookup_context.template_exists?("embedcode", resourceClassName.pluralize, true) %>
<% canBeShared = true %>
<% canBeDownloaded = true %>
<% canBeDownloadedInSCORM = ["presentation"].include?(resourceClassName) %>
<% showFullScreen = ["presentation"].include?(resourceClassName) %>
<% canBeCloned = ["presentation"].include?(resourceClassName) %>

<div class="tooltab_buttons">
  <% if showFullScreen %>
    <a href="<%=polymorphic_path(resource, :format => 'full')%>" target="_blank">
      <button class="movle_button"><span title='<%=t("dictionary.full_screen")%>' class="glyphicon glyphicon-fullscreen"></span></button>
    </a>
  <% end %>
  <% if can? :update, resource %>
    <%= link_to(edit_polymorphic_path(resource), :title => t("dictionary.edit")) do %>
      <button class="movle_button"><span class="glyphicon glyphicon-edit"></span></button>
    <% end %>
  <%end%>
  <% if canBeCloned and can? :update, resource %>
    <a href="<%=polymorphic_path(resource)+'/clone'%>" data-confirm="<%=t('dictionary.are_you_sure')%>" data-ok-button="<%=t('dictionary.ok')%>" data-cancel-button="<%=t('dictionary.cancel')%>" data-method="get" rel="nofollow">
      <button class="movle_button"><span title='<%=t("dictionary.clone")%>' class="glyphicon glyphicon-duplicate"></span></button>
    </a>
  <% end %>
  <% if can? :destroy, resource %>
    <a href="<%=polymorphic_path(resource)%>" data-confirm="<%=t('dictionary.are_you_sure')%>" data-ok-button="<%=t('dictionary.ok')%>" data-cancel-button="<%=t('dictionary.cancel')%>" data-method="delete" rel="nofollow">
      <button class="movle_button"><span title='<%=t("dictionary.delete")%>' class="glyphicon glyphicon-trash"></span></button>
    </a>
  <% end %>
</div>

<ul class="nav nav-tabs tooltab">
  <li class="active">
    <a href="#tab1" tabTitle='description' data-toggle="tab">
      <span class="hidden-xs"><%=t("resources.tools.description")%></span>
    </a>
  </li>
  <%if canBeEmbeded %>
    <li>
      <a href="#tab2" tabTitle='embed' data-toggle="tab">
        <span class="hidden-xs"><%=t("resources.tools.insert")%></span>
      </a>
    </li>
  <% end %>
  <li>
    <a href="#tab3" tabTitle='share' data-toggle="tab">
      <span class="hidden-xs"><%=t("resources.tools.share")%></span>
    </a>
  </li>
  <li>
    <a href="#tab4" tabTitle='download' data-toggle="tab">
      <span class="hidden-xs"><%=t("resources.tools.download")%></span>
    </a>
  </li>
</ul>

<div class="tab-content">

  <!-- Tab1 / description -->
  <div class="tab-pane active" id="tab1">
    <% unless resource.description.blank? %>
      <p class="resource_description"><%=resource.description%></p>
    <% else %>
      <div class="no_description"><%=t("resources.tools.description_no")%></div>
    <% end %>
    <% if canBeDownloadedInSCORM %>
      <p class="resource_metadata_link_wrapper"><a href="<%=metadata_resource_path(resource)%>" target="_blank"><%=t("resources.tools.view_metadata")%></a></p>
    <% end %>
  </div>

  <!-- Tab2 / embed -->
  <%if canBeEmbeded %>
    <div class="tab-pane" id="tab2">
      <div class="input-group">
        <textarea class="form-control" readonly="true" id="textarea_embed" type="text" style="overflow:auto;resize:none"><%= render partial: "#{ resourceClassName.tableize }/embedcode", locals: { resourceClassName.to_sym => resource } %></textarea>
        <div class="input-group-addon">
          <div data-toggle="tooltip" data-placement="right" title="<%=t("resources.tools.text_copy")%>">
            <button id="btn_copy_embed">
              <span class="glyphicon glyphicon-share"></span>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!-- Tab3 / share -->
  <% if canBeShared %>
    <% sharedURL = request.protocol + request.env['HTTP_HOST'].sub(/^(m|www)\./, '') + polymorphic_path(resource) %>
    <div class="tab-pane" id="tab3">
      <div class="input-group">
        <input class="form-control" readonly="true" id="input_with_sharedURL" type="text" value="<%=sharedURL%>"/>
        <div class="input-group-addon">
          <div data-toggle="tooltip" data-placement="right" title="<%=t("resources.tools.text_copy")%>">
            <button id="btn_copy_share">
              <span class="glyphicon glyphicon-share"></span>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!-- Tab4 / download -->
  <%if canBeDownloaded %>
    <div class="tab-pane" id="tab4">
        <% if canBeDownloadedInSCORM %>
          <button class="movle_button"><a href='<%=polymorphic_path(resource, :format => "scorm", :version => "12")%>'><span class="glyphicon glyphicon-download"></span>SCORM 1.2</a></button>
          <button class="movle_button"><a href='<%=polymorphic_path(resource, :format => "scorm", :version => "2004")%>'><span class="glyphicon glyphicon-download"></span>SCORM 2004</a></button>
        <% else %>
          <button class="movle_button"><a href='<%=download_resource_path(resource)%>'><span class="glyphicon glyphicon-download"></span><%=t("dictionary.download")%></a></button>
        <% end %>
    </div>
  <% end %>

</div>

<script>
  document.addEventListener("DOMContentLoaded", function(){
    var embedEvents = false;
    var shareEvents = false;
    var mytxt;

    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      // e.target // activated tab
      // e.relatedTarget // previous tab
      var loadedTab = $(e.target).attr("tabTitle");
      switch (loadedTab){
        case "embed":
          if(!embedEvents){
            embedEvents = true;
            $('button#btn_copy_embed').zclip({
              path:'/assets/ZeroClipboard.swf',
              copy:function(){
                return $('#textarea_embed').text();
              }
            });
            $("#textarea_embed").mouseup(function(e){
              // fixes safari/chrome problem
              e.preventDefault();
            }).focus(function(e){
              mytxt = $(this).text();
              $(this).select();
            }).click(function(e){
              mytxt = $(this).text();
              $(this).select();
            });
          }
          break;
        case "share":
          if(!shareEvents){
            shareEvents = true;
            $('button#btn_copy_share').zclip({
              path:'/assets/ZeroClipboard.swf',
              copy:function(){
                return $('#input_with_sharedURL').val();
              }
            });
            $("#input_with_sharedURL").mouseup(function(e){
              // fixes safari/chrome problem
              e.preventDefault();
            }).focus(function(e){
              mytxt = $(this).text();
              $(this).select();
            }).click(function(e){
              mytxt = $(this).text();
              $(this).select();
            });
          }
          break;
        default:
          break;
      }
    });
  });
</script>