config/routes.rb
Rails.application.routes.draw do
  root "home#frontpage"

  #Home
  match '/home' => 'home#home', via: [:get]

  #Search
  match '/search', to: 'search#index', via: [:get], as: 'search'

  #Users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  match '/users/:id/presentations' => 'users#show_presentations', via: [:get]
  match '/users/:id/files' => 'users#show_files', via: [:get]
  match '/users/:id/embeds' => 'users#show_embeds', via: [:get]

  #Documents
  resources :embeds
  resources :links
  resources :documents
  resources :pictures
  resources :zipfiles
  resources :officedocs
  resources :scormfiles
  match '/documents/:id/download' => 'documents#download', :via => :get
  match '/pictures/:id/download' => 'documents#download', :via => :get
  match '/zipfiles/:id/download' => 'documents#download', :via => :get
  match '/officedocs/:id/download' => 'documents#download', :via => :get
  match '/scormfiles/:id/download' => 'scormfiles#download', :via => :get

  #Presentations
  match '/presentations/:id/metadata' => 'presentations#metadata', :via => :get
  match '/presentations/:id/scormMetadata' => 'presentations#scormMetadata', :via => :get
  match '/presentations/:id/clone' => 'presentations#clone', :via => :get
  match '/presentations/last_slide' => 'presentations#last_slide', :via => :get
  match '/presentations/preview' => 'presentations#preview', :via => :get
  match '/presentations/tmpJson' => 'presentations#uploadTmpJSON', :via => :post
  match '/presentations/tmpJson' => 'presentations#downloadTmpJSON', :via => :get
  resources :presentations

  #PDF to Presentation
  resources :pdfps, :except => [:index]

  #Locale
  match '/change_locale', to: 'locales#change_locale', via: [:get]

  #Thumbnails
  match '/thumbnails' => 'presentations#presentation_thumbnails', via: [:get]

  #Tags
  match "/tags" => 'tags#index', :via => :get

  #Terms of use
  match '/terms_of_use', to: "home#frontpage", via: [:get]

  #Wildcard route (This rule should be placed the last)
  match "*not_found", :to => 'application#page_not_found', via: [:get]
end

app/models/embed.rb
class Embed < ActiveRecord::Base
    include Item
    belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  
    validates_presence_of :owner_id
    validates_presence_of :title
    validate :owner_validation
  
    def as_json(options = {})
        {
          id: id,
          title: title,
          description: description,
          iframe: iframe
        }
    end
      
end
  

app/controllers/embeds_controller.rb
class EmbedsController < ApplicationController
    before_action :authenticate_user!, :except => [:show]
    load_and_authorize_resource :except => [:download]
  
    def create
        @embed = Embed.create(embed_params)
            
        respond_to do |format|
            if @embed.persisted?
            format.json {
                render :json => @embed.to_json(:protocol => request.protocol)
            }
            format.html {
                redirect_to polymorphic_path(@embed), notice: I18n.t("documents.messages.success.create")
            }
            else
            format.json {
                return head(:not_found)
            }
            format.html { 
                flash.now[:alert] = @embed.errors.full_messages
                render action: "new"
            }
            end
        end
    end

    def show
      @document = Document.find_by_id(params[:id])
      respond_to do |format|
        format.json {
          render :json => @document.to_json 
        }
        format.html {
          @suggestions = RecommenderSystem.suggestions({:n => 6, :lo_profile => @document.profile, :settings => {}})
        }
        format.any {
          path = @document.file.path(params[:style] || params[:format])
          head(:not_found) and return unless (File.exist?(path) and request.format.nil? == false)
          send_file path,
                   :filename => @document.file_file_name,
                   :disposition => "inline",
                   :type => request.format
        }
      end
    end
  
    def update
      @embed = Embed.find_by_id(params[:id])
      respond_to do |format|
        if @embed.update(embed_params)
          format.html { redirect_to embed_path(@embed), notice: I18n.t("embeds.messages.success.update") }
        else
          format.html {
            flash.now[:alert] = I18n.t("embeds.messages.error.generic_update")
            render action: "edit"
          }
        end
      end
    end
  
    def new
    end
  
    def edit
      @embed = Embed.find_by_id(params[:id])
    end
  
    def destroy
      @embed = Embed.find_by_id(params[:id])
      @embed.destroy
  
      respond_to do |format|
        format.html {
          redirect_to view_context.current_user_path_for("files")
        }
        format.json { head :no_content }
      end
    end
  
    private

    def embed_params
        params.require(:embed).permit(:title, :description, :iframe, :owner_id)
    end
  end
  

app/views/embeds/_embed.html.erb
<% generated_id= "embed-" + embed.id.to_s %>
<div class="item_box item_box_embed_link">
  <div class="item_thumbnail">
    <%= link_to(embed_url(embed)) do %>
      <div class="embed_img">
        <img src="/assets/link-circle-fill.png"/>
      </div>
    <%end%>
  </div>
  <div class="item_title">
    <%= link_to(embed_url(embed)) do %>
      <p class="title"><%= embed.title %></p>
    <%end%>
  </div>
  <div class="item_user">
    <div class="d-flex by_date justify-content-between">
      <span class="author">
        <span class="by"><%=t('by')%></span>
        <%= link_to User.find_by(id: embed.owner_id)&.name, user_path(embed.owner_id) if embed.owner_id.present? %>
      </span>
      <span><%= embed.created_at.strftime('%d/%m/%Y') %></span>
    </div>
  </div>
  <div id="delete_link">
    <a href="<%=polymorphic_path(embed)%>" data-confirm="<%=t('dictionary.are_you_sure')%>" data-ok-button="<%=t('dictionary.ok')%>" data-cancel-button="<%=t('dictionary.cancel')%>" data-method="delete" rel="nofollow">
      <button class="movle_button"><span title='<%=t("dictionary.delete")%>' class="glyphicon glyphicon-trash"></span></button>
    </a>
  </div>
</div>

app/views/embeds/_new.html.erb
<%= form_with(model: Embed.new, url: embeds_path, method: :create) do |f| %>
  <%= f.hidden_field :owner_id, :value => current_user.id %>
  <div class="field">
    <p class="form_legend"><%=t("dictionary.embed")%></p>
    <%= f.text_field :iframe, :class => "outlined_input iframe" %>
  </div>
  <div class="field">
    <p class="form_legend"><%=t("dictionary.title")%></p>
    <%= f.text_field :title, :class => "outlined_input title" %>
  </div>
  <div class="field">
    <p class="form_legend"><%=t("dictionary.description")%></p>
    <%= f.text_area :description, {class: "description"} %>
  </div>
  <div class="actions">
    <%= f.submit('Subir Embed', {class: "movle_button upload_button"}) %>
  </div>
<% end %>

app/views/embeds/show.html.erb
<div id="embed-show">
  <h1><%= @embed.title %></h1>
  <span class="embed-description"><strong>Descripción:</strong> <%= @embed.description %></span>
  <%= raw @embed.iframe %>
</div>