config/routes.rb
Rails.application.routes.draw do
  root "home#frontpage"

  #Home
  match '/home' => 'home#home', via: [:get]

  #Search
  match '/search', to: 'search#index', via: [:get], as: 'search'

  #Users
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  match '/users/:id/presentations' => 'users#show_presentations', via: [:get]
  match '/users/:id/files' => 'users#show_files', via: [:get]
  match '/users/:id/embeds' => 'users#show_embeds', via: [:get]

  #Documents
  resources :embeds
  resources :links
  resources :documents
  resources :pictures
  resources :zipfiles
  resources :officedocs
  resources :scormfiles
  match '/documents/:id/download' => 'documents#download', :via => :get
  match '/pictures/:id/download' => 'documents#download', :via => :get
  match '/zipfiles/:id/download' => 'documents#download', :via => :get
  match '/officedocs/:id/download' => 'documents#download', :via => :get
  match '/scormfiles/:id/download' => 'scormfiles#download', :via => :get

  #Presentations
  match '/presentations/:id/metadata' => 'presentations#metadata', :via => :get
  match '/presentations/:id/scormMetadata' => 'presentations#scormMetadata', :via => :get
  match '/presentations/:id/clone' => 'presentations#clone', :via => :get
  match '/presentations/last_slide' => 'presentations#last_slide', :via => :get
  match '/presentations/preview' => 'presentations#preview', :via => :get
  match '/presentations/tmpJson' => 'presentations#uploadTmpJSON', :via => :post
  match '/presentations/tmpJson' => 'presentations#downloadTmpJSON', :via => :get
  resources :presentations

  #PDF to Presentation
  resources :pdfps, :except => [:index]

  #Locale
  match '/change_locale', to: 'locales#change_locale', via: [:get]

  #Thumbnails
  match '/thumbnails' => 'presentations#presentation_thumbnails', via: [:get]

  #Tags
  match "/tags" => 'tags#index', :via => :get

  #Terms of use
  match '/terms_of_use', to: "home#frontpage", via: [:get]

  #Wildcard route (This rule should be placed the last)
  match "*not_found", :to => 'application#page_not_found', via: [:get]
end

app/views/layouts/_data_warning.html.erb
<div id="data_warning_wrapper">
	<div id="data_warning">
		<div id="data_warning_row1">
			<%=t("data_warning.content")%>
		</div>
		<div id="data_warning_row2">
			<button id="data_warning_button"><%=t("data_warning.button")%></button>
		</div>
	</div>
</div>

<script type="text/javascript">
	var localStorageSupported = function(){
		return (!!window.localStorage
    		&& typeof localStorage.getItem === 'function'
    		&& typeof localStorage.setItem === 'function'
    		&& typeof localStorage.removeItem === 'function');
	};

	var showWarning = function(){
		var lsSupported = localStorageSupported();

		//Show warning only if necessary
		if(lsSupported === true){
			if(window.localStorage.getItem('data_warning')==='true'){
				//Do not show data warning because it has been previously shown
				return;
			}
		}

		$("#data_warning_button").click(function(){
			if(lsSupported === true){
				window.localStorage.setItem('data_warning','true');
			}
			$("#data_warning_wrapper").hide();
		});

		$("#data_warning_wrapper").show();
	}

	showWarning();
</script>

app/views/layouts/_footer.html.erb
<div class="col1">
  <img class="icon" src="/assets/escudo_upm.png"/>
</div>
<div class="col3">
  <div class="dropup footer_dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="bi bi-info-circle-fill"></i>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <% if Movle::Application.config.APP_CONFIG["mail"] and Movle::Application.config.APP_CONFIG["mail"]["main_mail"] %>
        <li><a href=<%="mailto:" + Movle::Application.config.APP_CONFIG["mail"]["main_mail"]%>><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><span><%=t("footer.contact")%></span></a></li>
      <% end %>
      <li><a href="https://github.com/ging/MOVLE" target="_blank"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span><%=t("footer.code")%></a></li>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
    <%= render "layouts/header_identified" %>
<% else %>
  <%= render "layouts/header_anonymous" %>
<% end %>

app/views/layouts/_header_anonymous.html.erb
<div id="movle_logo_wrapper">
  <a href="/">
    <p class="logo">MOVLE</p>
  </a>
</div>
<div id="buttons_header">
  <%= render partial: 'layouts/search' %>
  <div class="dropdown header_dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <img src="/assets/flags/flag_<%=I18n.locale.to_s%>.png"/>
      <div>
        <span class="languagetext"><%=t("dictionary.language")%></span>
      </div>
    </button>
    <ul class="dropdown-menu">
      <form id="change_locale" action="/change_locale" action="GET">
        <input name="locale" value="" type="hidden"/>
        <% I18n.available_locales.map(&:to_s).each do |lanCode| %>
          <li value="<%=lanCode%>"><img src="/assets/flags/flag_<%=lanCode%>.png"/><%=t("languages." + lanCode)%></li>
        <% end %>
      </form>
    </ul>
  </div>
  <div class="movle_secondary_button movle_secondary_button_header" id="register_wrapper">
    <a href="/users/sign_up"><%=t("dictionary.register")%></a>
  </div>
  <div class="movle_button movle_button_header" id="login_wrapper">
    <a href="/users/sign_in"><%=t("dictionary.login")%></a>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#change_locale li").click(function(e){
      $("#change_locale input[name]").attr("value",$(this).attr("value"));
      $("#change_locale").submit();
    });
  });
</script>

app/views/layouts/_header_identified.html.erb
<div id="movle_logo_wrapper">
  <a href="/">
    <p class="logo">MOVLE</p>
  </a>
</div>
<div id="buttons_header_identified">
  <%= render partial: 'layouts/search' %>
  <div id="header_plus_wrapper" class="dropdown">
    <button class="dropdown-toggle movle_button" type="button" data-toggle="dropdown">
      +
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
      <li><%= link_to(t("documents.new"),new_document_path())%></li>
      <li><%= link_to(t("presentations.new"),new_presentation_path())%></li>
    </ul>
  </div>
  <div id="header_profile" class="dropdown">
    <button class="dropdown-toggle movle_button" type="button" data-toggle="dropdown">
      <%= current_user.name %>
    </button>
    <ul class="dropdown-menu dropdown-menu-right">
      <div id="arrow-up-header-profile"></div>
      <li><%= link_to(t("header.menu.profile"),user_path(current_user))%></li>
      <li><%= link_to(t("header.menu.settings"),edit_user_registration_path(current_user))%></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to(t("header.menu.logout"), destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </div>
</div>

app/views/layouts/_notification.html.erb
<% alertType ||= "danger" %>
<% alertClass = (alertType=="success") ? "alert-success" : ((alertType=="warning") ? "alert-warning" : "alert-danger") %>
<% dismissable ||= true %>
<% dismissableClass = (dismissable==true) ? "alert-dismissable" : "" %>

<div class="alert <%=alertClass=%> <%=dismissableClass%> ">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<%= msg %>
</div>

app/views/layouts/_notifications.html.erb
<div id="movle_notifications">
	<% if flash[:notice] %>
		<% if flash[:notice].is_a? Array %>
			<% flash[:notice].uniq! %>
			<% flash[:notice].each do |msg| %>
				<%= render '/layouts/notification', :alertType => "success", :msg => msg %>
			<% end %>
		<% else %>
			<%= render '/layouts/notification', :alertType => "success", :msg => flash[:notice] %>
		<% end %>
	<% end %>

	<% if flash[:alert] %>
		<% if flash[:alert].is_a? Array %>
			<% flash[:alert].uniq! %>
			<% flash[:alert].each do |msg| %>
				<%= render '/layouts/notification', :alertType => "danger", :msg => msg %>
			<% end %>
		<% else %>
			<%= render '/layouts/notification', :alertType => "danger", :msg => flash[:alert] %>
		<% end %>
	<% end %>

	<% if flash[:warning] %>
		<% if flash[:warning].is_a? Array %>
			<% flash[:warning].uniq! %>
			<% flash[:warning].each do |msg| %>
				<%= render '/layouts/notification', :alertType => "warning", :msg => msg %>
			<% end %>
		<% else %>
			<%= render '/layouts/notification', :alertType => "warning", :msg => flash[:warning] %>
		<% end %>
	<% end %>
</div>

app/views/layouts/_search.html.erb
<%= javascript_include_tag 'search' %>
<div id="search">
  <%= form_tag search_path, method: 'get' do %>
    <%= text_field_tag :q, nil, autocomplete: :off, class: 'search-query form-control', placeholder: t('dictionary.search') %>
    <button type="button" id="search_button_desktop"><i class="fas fa-search"></i></button>
  <% end %>
</div>
<script>
  $("#search_button_desktop").on("click", function(){
    var searchQuery = $("#q").val();

    if (searchQuery.trim() !== "") {
      document.location= "/search?q=" + $("#q").val();
    } else {
      document.location= "/search"
    }
  });
</script>

app/views/layouts/_veditor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=@presentation.title unless @presentation.nil?%></title>
    <%= favicon_link_tag "/assets/favicon.ico" %>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>

    <% if controller.action_name == "show" %>
      <%js_file = "vishViewer"%>
    <% else %>
      <%js_file = "vishEditor"%>
      <script type="text/javascript">
        var CKEDITOR_BASEPATH = '/assets/ckeditor/';
      </script>
      <%= javascript_include_tag "ckeditor/ckeditor" %>
    <% end %>

    <% if Rails.env == "production" %>
      <%= javascript_include_tag js_file + ".min" %>
    <% else %>
      <%= javascript_include_tag js_file %>
    <% end %>

    <%= stylesheet_link_tag "vish_editor" %>

    <%= yield :headers %>
  </head>

  <body onload="start()" style="display: none" class="loaded">
    <%= yield %>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOVLE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "/assets/favicon.ico" %>
    <meta charset="UTF-8">
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/data_warning" %>
      <header id="header">
        <%= render "layouts/header" %>
      </header>
      <div id="container">
        <div id="over">
          <%= render '/layouts/notifications' %>
        </div>
        <%= yield %>
        <footer id="footer">
          <%= render "layouts/footer" %>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/layouts/iframe.full.erb
<!DOCTYPE html>
<html>
  <head>
    <%if @title%>
      <title><%=@title%></title>
    <% end %>
    <%= favicon_link_tag "/assets/favicon.ico" %>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <style type="text/css">
      html, body {
        width: 100%;
        height: 100%;
        overflow: hidden;
        margin: 0px !important;
      }
    </style>
    <%= yield :headers %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/veditor.full.erb
<%= render(:partial => 'layouts/veditor', :formats => [:html]) %>